# Generated by Django 5.2.6 on 2025-10-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcreator',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourcreator',
            name='username',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
