# Generated by Django 5.2.6 on 2025-10-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_alter_tourcreator_phone_alter_tourcreator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcreator',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
