# Generated by Django 5.2.6 on 2025-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_tourcreator_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcreator',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
    ]
