# Generated by Django 5.2.6 on 2025-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_tourcreator_groups_tourcreator_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
