# Generated by Django 5.2.7 on 2025-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_attractionsite_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcreator',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tourcreator',
            name='reg_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
