# Generated by Django 5.2.7 on 2025-10-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_alter_tourcreator_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionsite',
            name='image',
            field=models.ImageField(default=1, upload_to='sites'),
            preserve_default=False,
        ),
    ]
